---
title: "Data Import"
output: github_document
---

```{r, setup}
library(tidyverse)
```

## Read in some data

Lets import the 'FAS_litters.csv' csv using a relative path. 
```{r}
litters_df = 
  read_csv("data/FAS_litters.csv")

## this will clean up the data and make it more readable

litters_df = 
  janitor::clean_names(litters_df)
  
```
## Now lets take a look at the clean data

Printing in the console. 

```{r}
litters_df
```


```{r}
## this shows the top and bottom few rows of the dataset. 
head(litters_df)
tail(litters_df)
```
```{r}
skimr::skim(litters_df)
```

## Other options to read_csv (looking at the help file)

```{r}
litters_df = read_csv("data/FAS_litters.csv", skip = 10, col_names = FALSE)
```

Lets look at NA values. 
```{r}
litters_df = read_csv("data/FAS_litters.csv", na = c("NA", 19))
```

Check out: '?read_csv()' for more information. 

## Learning Assessment
Repeat the data import process for pups. 

```{r}
pups_df = read_csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```




